### ISSUE TITLE
Problem with Picoscope 2204A

### ISSUE THREAD

**Issue by larrygorham** [GuenterQuast/PhyPiDAQ#11]
Problem with erratic data collection using ./run_phypi.py PhyPiConf.daq after editing  PhyPiConf.daq and PSConfig2000A.yaml to suit. Picoscope works ok with Picolog from Picoscope.com. I may have missed something. Thanks.
[cli_output.txt](https://github.com/GuenterQuast/PhyPiDAQ/files/6131446/cli_output.txt)
[PhyPiConf.daq.txt](https://github.com/GuenterQuast/PhyPiDAQ/files/6131448/PhyPiConf.daq.txt)
[PSConfig2000A.yaml.txt](https://github.com/GuenterQuast/PhyPiDAQ/files/6131449/PSConfig2000A.yaml.txt)
[run_phypi.py.txt](https://github.com/GuenterQuast/PhyPiDAQ/files/6131450/run_phypi.py.txt)

**Comment by GuenterQuast** [comment]
The input files and the output produced look reasonable, the PicoScope apporoximately used your proposed
settings (time between samplings 0.08µs, 250 Samples). So, the problem must be elsewhere ...

Could you be a bit more specific about your problem, and what you intend to do with your settings?

Here a short description of what your configurations do:
You are reading 20 times/sec a 20µs long sample, of which the module phypidaq/PSConfig.py returns only the average. You are also using a very low range of 50mV only, and therefore you may be very sensitive to noise. The average of such noise results in "erratic" measurements - is that what you observe ?

You might try to take snapshots of your signal (with the picoScop software, or with the oscilloscope module 
examples/runOsci.py with your configuration file). Are the pictures stable ? 
If you are measuring an AC voltage, the option  ChanAverage: ['rms'] may help, because that returns the effective voltage, and not the mean, which is of course close to zero for an AC voltage (except for noise effects)).

**Comment by larrygorham** [comment]
Dear Gunter
Danka for your help, it's tremendous. I found no other code that works on the Raspberry CLI. My signal 1.5 v maxes around 20 hz modulated on a tiny varying ~600 kHz carrier. Since phypidaq fastest sampling is 20 hz I had hoped to double that but you can see the result (DGraphs.png) at 9 hz. Dgraphs1.png is the result I got before the rms change. The data files show the same. The driver is a smooth 9 hz signal with no carrier and no noise. I made the rms change you suggested. All else is the same as before. CLI follows:
######################
***@***.***:~/git/PhyPiDAQ $ ./run_phypi.py PhyPiConf.daq
  Configuration from file PhyPiConf.daq
  configuring device PSConfig
  Pretrig sampling disabled on device  2000
      picoIni: sampling interval = 0.08 µs (0.1 µs)
      picoIni: number of samples = 250 (200)
      picoIni: range channel A: 2V (2V)
      picoIni: channel offset A: 0V
      picoIni: picoIni: trigger inactive
Channel 0: averaging mode= rms
  storing data to file  testfile.csv

PhyPiDAQ Configuration:
CSVseparator: ;
ChanAverage: [rms]
ChanColors: [darkblue, sienna]
ChanLabels: ['']
ChanLimits:
- !!python/tuple [-2.0, 2.0]
ChanNams: [A]
ChanUnits: ['']
DAQfifo: null
DataFile: testfile.csv
DeviceFile: config/PSConfig2000A.yaml
DisplayModule: DataLogger
Interval: 0.05
NChannels: 1
NHistoryPoints: 60
XYmode: false
bufferData: PhyPiData
startActive: true

DAQ set-up:
 CSVseparator: ;
ChanAverage: [rms]
ChanColors: [darkblue, sienna]
ChanLabels: ['']
ChanLimits:
- !!python/tuple [-2.0, 2.0]
ChanNams: [A]
ChanUnits: ['']
DAQfifo: null
DataFile: testfile.csv
DeviceFile: config/PSConfig2000A.yaml
DisplayModule: DataLogger
Interval: 0.05
NChannels: 1
NHistoryPoints: 60
XYmode: false
bufferData: PhyPiData
startActive: true

*==* script ./run_phypi.py: data taking active

                    type -> P(ause), R(esume), E(nd) or s(ave) + <ret>
######################

The oscilloscope module would probably solve my problem but I was unable to get it to work as you can see:

################

***@***.***:~/git/PhyPiDAQ $ ./examples/runOsci.py PhyPiConf.daq

*==* script ./examples/runOsci.py running

    PS configuration from file PhyPiConf.daq
    Device configuration from file PhyPiConf.daq
!!! PSconfig:  Error initialising device
Error calling _lowLevelOpenUnit: PICO_NOT_FOUND (No PicoScope XXXX could be found.)
  - exiting
#############################

Thank you very much,
Larry

________________________________

**Comment by larrygorham** [comment]
This was my mistake in understanding the data acquisition of run_phypi.py which has a maximum collection rate of 20 hz. Run_phypi.py is collecting correctly. The data appeared gapped because of aliasing. Since I need a much faster rate I will continue to work with runOsci.py which should solve my problem.
Thanks,
Larrry

**Comment by larrygorham** [comment]
I have runOsci.py  working now using my changed PSConfig2000A.yaml.
Thanks again
Larry
